name: 'Agentrial CI'
description: 'Statistical evaluation for AI agents - test your agents with confidence intervals and failure attribution'
author: 'Alessandro Potenza'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  trials:
    description: 'Number of trials per test case'
    required: false
    default: '10'
  threshold:
    description: 'Minimum pass rate (0-1) to pass CI'
    required: false
    default: '0.9'
  config:
    description: 'Path to agentrial.yml config file'
    required: false
    default: 'agentrial.yml'
  test-path:
    description: 'Path to test files or directory'
    required: false
    default: 'tests/'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  post-comment:
    description: 'Post results as PR comment'
    required: false
    default: 'true'

outputs:
  pass-rate:
    description: 'Overall pass rate'
    value: ${{ steps.run.outputs.pass_rate }}
  passed:
    description: 'Whether the evaluation passed the threshold'
    value: ${{ steps.run.outputs.passed }}
  results-file:
    description: 'Path to JSON results file'
    value: ${{ steps.run.outputs.results_file }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Agentrial
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install agentrial

    - name: Install project dependencies
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f pyproject.toml ]; then
          pip install -e . || true
        fi

    - name: Run Agentrial
      id: run
      shell: bash
      run: |
        set +e
        agentrial run ${{ inputs.test-path }} \
          --trials ${{ inputs.trials }} \
          --threshold ${{ inputs.threshold }} \
          --output agentrial-results.json \
          2>&1 | tee agentrial-output.txt
        EXIT_CODE=$?
        set -e

        # Parse results for outputs
        if [ -f agentrial-results.json ]; then
          PASS_RATE=$(python -c "import json; d=json.load(open('agentrial-results.json')); print(d.get('summary', {}).get('overall_pass_rate', 0))")
          PASSED=$(python -c "import json; d=json.load(open('agentrial-results.json')); print('true' if d.get('summary', {}).get('passed', False) else 'false')")
        else
          PASS_RATE="0"
          PASSED="false"
        fi

        echo "pass_rate=$PASS_RATE" >> $GITHUB_OUTPUT
        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "results_file=agentrial-results.json" >> $GITHUB_OUTPUT

        exit $EXIT_CODE

    - name: Post PR Comment
      if: ${{ inputs.post-comment == 'true' && github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          let results;
          try {
            results = JSON.parse(fs.readFileSync('agentrial-results.json', 'utf8'));
          } catch (e) {
            console.log('No results file found, skipping comment');
            return;
          }

          const summary = results.summary || {};
          const passed = summary.passed ? ':white_check_mark: Passed' : ':x: Failed';
          const passRate = (summary.overall_pass_rate * 100).toFixed(1);
          const ci = summary.overall_pass_rate_ci || {};
          const ciLower = ((ci.lower || 0) * 100).toFixed(0);
          const ciUpper = ((ci.upper || 0) * 100).toFixed(0);
          const cost = (summary.total_cost || 0).toFixed(4);

          let body = `## Agentrial Results ${passed}\n\n`;
          body += `**Overall Pass Rate:** ${passRate}% (95% CI: ${ciLower}%-${ciUpper}%)\n`;
          body += `**Total Cost:** $${cost}\n\n`;

          body += `### Test Results\n\n`;
          body += `| Test Case | Pass Rate | 95% CI | Avg Cost | Avg Latency |\n`;
          body += `|-----------|-----------|--------|----------|-------------|\n`;

          for (const r of (results.results || [])) {
            const tc = r.test_case || {};
            const pr = (r.pass_rate * 100).toFixed(0);
            const prCi = r.pass_rate_ci || {};
            const ciStr = `${((prCi.lower || 0) * 100).toFixed(0)}%-${((prCi.upper || 0) * 100).toFixed(0)}%`;
            const avgCost = (r.mean_cost || 0).toFixed(4);
            const avgLatency = (r.mean_latency_ms || 0).toFixed(0);
            body += `| ${tc.name || 'unknown'} | ${pr}% | ${ciStr} | $${avgCost} | ${avgLatency}ms |\n`;
          }

          // Check for existing comment to update
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(c => c.body.includes('## Agentrial Results'));

          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }

    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: agentrial-results
        path: agentrial-results.json
        retention-days: 30
